### ISSUE TITLE
VisualScript purpose might be misleading

### ISSUE THREAD

**Issue by Xrayez** [Vivraan/godot-lang-support#1]
https://github.com/Vivraan/godot-lang-support/blob/2fccfb9d68f47472cdbbbe7da0c3f25e50cd6019/README.md#L32

See my comment in https://github.com/godotengine/godot/issues/30915#issuecomment-664016434.

Compare reduz response:

> Unlike Unreal, this is more meant as a complement to programmers, so game designers, level designers, etc. can work more easily.

I'm not quite sure about this statement, but I kind of doubt for this opinion to be outdated even in 2020.

The thing is that 99% of people do think VisualScript is indended for *non-programmers* in spite of this. So I'd just combine the two statements perhaps, because by now the community's effort is to make it easy-to-use even for non-programmers?

There are certainly engines which target "no coding required" philosophy, better than Godot IMO, of course they're more limited in comparison.

**Comment by Vivraan** [comment]
Just omitting the "non-programmers" part should do I guess.

**Comment by Vivraan** [comment]
I also added a summary of what I read in the thread you shared.

**Comment by Xrayez** [comment]
I think this should do it, closing but up for discussion of course, if you like. 🙂
