### ISSUE TITLE
New Go bindings available

### ISSUE THREAD

**Issue by pycbouh** [Vivraan/godot-lang-support#10]
Current doc lists an old repository with Go bindings, seemingly being abandoned (https://github.com/ShadowApex/godot-go).

User `surgical#3758` on Discord just announced a new project of theirs, claiming it to be ready for "alpha use": https://github.com/godot-go/godot-go/

We should probably mention it in the list, but that raises a question of how to show contesting libraries in the best way as to not confuse readers? Here we can probably remove Go from `L4D` section or mark it as being replaced by something else. But there can be cases where different groups are working on the same language support, as was with Kotlin until recently.

**Comment by Vivraan** [comment]
> We should probably mention it in the list, but that raises a question of how to show contesting libraries in the best way as to not confuse readers? 

Just bump up the relevant Go binding to the new category. If multiple projects for a language compete on the same category, use a child list with the links or authors explicitly mentioned.

**Comment by pycbouh** [comment]
Yeah, but contesting versions can be in different categories of readiness. Unless put them all in the best possible and list other, less developed under the main entry.

**Comment by Vivraan** [comment]
You could totally put them in different categories. Entries for languages needn't be unique imo.
