### ISSUE TITLE
Frameworks and Tools

### ISSUE THREAD

**Issue by ShalokShalom** [Vivraan/godot-lang-support#14]
Let us collect Framework support?

https://github.com/alfredbaudisch/GodotPhoenixChannels

**Comment by Vivraan** [comment]
Nice idea for a new document!

We can change the subject of our repo then, make it like a community wiki of sorts, but let's focus on having the language list first I believe!

**Comment by ShalokShalom** [comment]
I wanted to make a community repo as well. 
I think linking between actual files is the easiest way.
So simply creating different documents and then linking between them.

**Comment by Vivraan** [comment]
The Wiki tab looks good but it won't support PRs.

**Comment by ShalokShalom** [comment]
I open a new issue.

**Comment by ShalokShalom** [comment]
https://github.com/GodotExplorer/godot-javascript-debug

**Comment by Vivraan** [comment]
Debugger support seems to be an additional feature for JS. What about other languages?

**Comment by ShalokShalom** [comment]
Yes, this is the question. We should ask the developers.
We can create a template, that we draft together and we send it then to the developers of the regarding implementations.

**Comment by Vivraan** [comment]
Yes please. This can also fit into #13.

**Comment by Vivraan** [comment]
#13 can host this as well.
