### ISSUE TITLE
Sort language list alphabetically, change grouping by ranking to grouping by maintainer

### ISSUE THREAD

**Issue by Vivraan** [Vivraan/godot-lang-support#15]
The reason for this proposition is:
1. There can be more than one implementation of a language binding, in which case separating them by rank may not be convenient for reading.
1. The new list can be sorted more conventionally as:
    ## {Language} {category-emoji}*
    1. ### {Implementation [0-9]+}
        {Description}

1. This is more easily maintainable as ranks can be added just like any other category emoji.

**Comment by pycbouh** [comment]
This does probably make more sense since people would mostly be interested in how well their favorite language holds and not an arbitrary gradation. Though I'd still probably keep GDScript and Godot's visual scripting at the top in a separate section, as those are Godot specific tools and should be mentioned as such.

**Comment by Vivraan** [comment]
Interesting, perhaps hint subliminally that you usually don't need to use anything else! ;)

**Comment by pycbouh** [comment]
> However, it is similar to just organising by Official and Community Support.

That would be precisely it, yes.

**Comment by Vivraan** [comment]
Maybe we should organise by maintainers instead. The Community bindings list is the one which is most likely to grow anyway.

**Comment by ShalokShalom** [comment]
List alphabetically within the categories yes
 I love this list first and foremost for the ordering by quality

**Comment by Vivraan** [comment]
> List alphabetically within the categories yes
> I love this list first and foremost for the ordering by quality

This does however separate bindings from the same language.

We could still move forward with reorganising the way the entries are written I guess.

**Comment by ShalokShalom** [comment]
Yeah, and separating language bindings of the same language is something very minor to me, while ordering the quality is all this repository is about. I love to have an overview, which languages are supported in which way and to which quality. This is 100% the purpose of this project in my perspective.

**Comment by Vivraan** [comment]
This would be much more fun if we could actually interactively sort entries by whichever criteria we put in. But that's a tale for another time.
