### ISSUE TITLE
New hosting at alternative platform

### ISSUE THREAD

**Issue by ShalokShalom** [Vivraan/godot-lang-support#17]
Github is a proprietary platform, so I considered replacing it. While I see an alternative, which might work more effectively: 

We could also use Github to contribute and link our mirrored instance, to expose the viewers to an alternative and make at least a little bit good karma this way. 😉 

This keeps the project easier to contribute to, since most people do use Github.

3 different open source alternatives to Github were tested:
, Phabricator, Gitea and Gitlab.

Phabricator, hosted at the community maintained gitpull.it
*coming soon*

Gitlab it extremely slow, the import was a pain. https://gitlab.com/ShalokShalom/godot-lang-support

Gitea seems to be the closest to Github, very fast:
https://gitea.com/ShalomShalom/godot-lang-support

My favorites: 

1) Gitea
2) Phabricator
3) Gitlab

What do you think of it?

Much fun 🥳

**Comment by lboklin** [comment]
I just want to bring attention to the existence of https://sr.ht/ which I've seen is gaining popularity in the FLOSS community.

**Comment by Vivraan** [comment]
Godot itself isn't mirrored on GitHub and maintained anywhere else. Having a mirror is fine but I expect most would-be contributors to have a GitHub account first (I use GitLab for my own projects btw), which would make the first step towards contributing more painful.

Also note that most of the bindings repos we list are on GitHub. If someone cross-references our issues or PRs or vice versa, imo it'd be better to remain within GitHub itself (although a hyperlink really doesn't pose this problem ig).

I'm also not acquainted with the immediate editing tools or cron job stuff on other Git hosting platforms, which may also have a non-flat learning curve for would-be contributors.

**Comment by pycbouh** [comment]
If someone wants to host a mirror on any other platform, that's trivial. Moving the whole contribution pipeline there would be detrimental, as described by Vivraan. I'm also kind of hoping for this repo to be included into the Godot organization at some point. It seems like a natural progression.

**Comment by ShalokShalom** [comment]
Yes, this is also how I feel. 🙂

**Comment by Vivraan** [comment]
I didn't intend it but if it became a part of the official Godot org I'd be on cloud nine!

**Comment by ShalokShalom** [comment]
I actually doubt it, since I see unofficially supported languages getting rejected by official members on the team on a regular basis, so they reject some documentation on them for sure. Happy to be proven incorrect. ^-^ 😇
