### ISSUE TITLE
ArcadiaGodot - Clojure

### ISSUE THREAD

**Issue by ryliejamesthomas** [Vivraan/godot-lang-support#28]
This was recently released. It adds Clojure support:

https://github.com/arcadia-unity/ArcadiaGodot | http://selfsamegames.com/pages/posts/arcadia-godot.html

**Comment by ShalokShalom** [comment]
Official thread for all future and current issues about this project on our page.

**Comment by Vivraan** [comment]
@ShalokShalom requesting you to use the new Discussions feature!
