### ISSUE TITLE
Category: by module support

### ISSUE THREAD

**Issue by Vivraan** [Vivraan/godot-lang-support#7]
```md
### (TODO)
(Per-module support feature legend. Currently, Rust (IIRC) doesn't support the video encoding module.)
```

This section should be removed and discussions on this should occur in this thread.

**Comment by willnationsdev** [comment]
> This section should be removed and discussions on this should occur in this thread.

I think the discussion on the particular Rust video encoding issue should be researched and come to a conclusion, at which point, we can create a definitive section in the README with that information. But I wouldn't just indefinitely keep this Issue open for "discussions on [module support]" (if that's what you meant). Just wanted to clarify.

**Comment by ShalokShalom** [comment]
I suggest an own dedicated page for each side on either the Wiki, or as an own separate document, that we can link to from the main Readme.

**Comment by Vivraan** [comment]
Would it be wise to shift the whole markdown content to wiki? The idea is that this would then behave more like a github.io page.

What would need to be done for that?

**Comment by ShalokShalom** [comment]
You mean an own homepage? They are done by Jekyll. You could also use one of these templates for it: https://themefisher.com/jekyll-documentation-themes/

In Gitlab, you can use all other static site generators, like Hugo

**Comment by Vivraan** [comment]
Ah yes, Jekyll. I guess we can keep this in a TO-DO list of some sort.

**Comment by Vivraan** [comment]
#13 supersedes this.
