### ISSUE TITLE
Relevant issues from other repositories

### ISSUE THREAD

**Issue by ShalokShalom** [Vivraan/godot-lang-support#8]
I suggest to link issues, who are relevent to the support.
Like: https://github.com/touilleMan/godot-python/issues/146

**Comment by Vivraan** [comment]
Indeed, sounds like a good cross-linking idea.

**Comment by ShalokShalom** [comment]
That here looks also like worth wile checking out.
I will post this here for now, and hope to become motivated enough to go through all implementations and look for corresponding links. Thanks a lot 

https://github.com/pragmagic/godot-nim/issues/66

**Comment by Vivraan** [comment]
This looks excellent. I'll try to catch up when I can.

**Comment by ShalokShalom** [comment]
I will leave that here: https://github.com/godotengine/godot-proposals/issues/191
